version: '3.8'

services:
  postgres:
    container_name: platform_programing_courses_postgres
    image: postgres
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=programing_courses